project:
  type: website

website:
  title: "PP2023"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/guebin/PP2023
      - icon: youtube
        href: https://www.youtube.com/channel/UCQk9RyBNgXc7ORIsYlOfQrg/playlists?view=50&sort=dd&shelf_id=2
    
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: false
    code-line-numbers: true
    code-copy: true